[theme]
primaryColor = "#10a37f"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f8"
textColor = "#202123"
font = "sans serif"

[server]
runOnSave = true

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false
